name: Build and Test

on:
  push:
    branches: [ "main", "ui-fixes", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y qt6-base-dev cmake g++ ninja-build avahi-daemon libavahi-client-dev pkg-config

    - name: Build C++ Desktop App
      run: |
        mkdir -p build
        cd build
        cmake .. -G Ninja
        ninja
        ./onenode_test

    - name: Upload Linux Binary
      uses: actions/upload-artifact@v4
      with:
        name: OneNode-Linux
        path: build/onenode

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.8.0'
        arch: 'win64_msvc2022_64'
    - name: Build C++ Desktop App
      run: |
        mkdir -p build
        cd build
        cmake .. 
        cmake --build . --config Release
    - name: Upload Windows Binary
      uses: actions/upload-artifact@v4
      with:
        name: OneNode-Windows
        path: build/Release/onenode.exe

  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x DropIn/gradlew

    - name: Build with Gradle
      run: |
        cd DropIn
        ./gradlew assembleDebug
        ./gradlew testDebugUnitTest

    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: OneNode-Android-APK
        path: DropIn/app/build/outputs/apk/debug/app-debug.apk
